version: '3.5'
services:
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - app:/var/www/html
  #   command: certonly --standalone --preferred-challenges http -d api-simpletrader.ngrok.com
  gateway-1:
    build:
      context: ./
      dockerfile:  Dockerfile
    # restart: unless-stopped
    hostname: gateway-1
    container_name: gateway-1
    tty: true
    env_file:
      - .one.env
    volumes:
      - app:/var/www/html
    # ports:
    #   - "9001:9001"
    command:
      - yarn
      - start-dev
  gateway-2:
    build:
      context: ./
      dockerfile:  Dockerfile
    # restart: unless-stopped
    hostname: gateway-2
    container_name: gateway-2
    tty: true
    env_file:
      - .two.env
    volumes:
      - app:/var/www/html
    command:
      - yarn
      - start-dev
  gateway-proxy:
    image: nginx:alpine
    container_name: gateway-proxy
    restart: unless-stopped
    depends_on:
      - gateway-1
      - gateway-2
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/certs/:/etc/nginx/ssl
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
volumes:
  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./
networks:
  default:
    name: 'simple-trader'
    external: true