version: '3.5'
services:
  gateway-1:
    build:
      context: ./
      dockerfile:  Dockerfile
    restart: always
    hostname: gateway-1
    container_name: gateway-1
    env_file:
      - .one.env
    volumes:
      - app:/var/www/html
    command:
      - yarn
      - start
  gateway-2:
    build:
      context: ./
      dockerfile:  Dockerfile
    restart: always
    hostname: gateway-2
    container_name: gateway-2
    env_file:
      - .two.env
    volumes:
      - app:/var/www/html
    command:
      - yarn
      - start
  gateway-proxy:
    image: nginx:alpine
    container_name: gateway-proxy
    restart: unless-stopped
    depends_on:
      - gateway-1
      - gateway-2
    ports:
      - 8000:8000
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
volumes:
  app:
networks:
  default:
    name: 'simple-trader'
    external: true